### ISSUE TITLE
Add Bookmark Support

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#29]
Decisions needed on how this is actually implemented.

**Comment by dodget** [comment]
@jamstooks - I am working on creating bookmarks/benchmarks in bt-backend today. Just to make sure that I'm on the right track, I should create a new app "benchmark" in bt-backend/bt/apps/ ?

**Comment by jamstooks** [comment]
@dodget  - that sounds like the right approach to me. The api app can provide the interface to the models created in that app.

**Comment by jamstooks** [comment]
Just adding a note here that bookmarks should be sharable.

**Comment by jamstooks** [comment]
@dodget 

Do you have a sense of how the sharing process would work for bookmarks?

What if someone just wants to share the screen they're looking at... how would that process work?
... create a bookmark and then share that? Seems like a lot of clicks. Should their be a separate "share" icon that displays a link and creates a bookmark as a side effect?

**Comment by jamstooks** [comment]
I guess I'm just curious if the `bookmark` icon will be intuitive enough for folks. Just from a UX standpoint it doesn't seem as obvious as a `share` icon...

Incidentally, I've been thinking about changing the navigation a bit... perhaps having all the fab buttons going down the right-hand side. Then we could add additional buttons, like "manage bookmarks" or something that pulls up a small dialog with a list of bookmarks and edit/delete/share options...

**Comment by dodget** [comment]
I'm not invested in the bookmark icon, since the action that they are taking is saving. I see sharing as a natural extension of saving, rather than saving as an extension of sharing. I thought a share icon would appear after a benchmark has been saved, or when a benchmark is loaded. When you click the icon, a click activate tooltip will appear with the public url.

Is that change in navigation a reaction to beta testing feedback? It seems like quite a departure.

**Comment by dodget** [comment]
Tested and implemented. Closing.
