### ISSUE TITLE
Choosing Metric Units Clears Out Percentages

### ISSUE THREAD

**Issue by peltonc** [AASHE/bt#55]
Using IP units only means that this tool is not going to be very useful for institutions in Canada and elsewhere. Can we add a toggle to the landing page with SI (metric) units being the default?

**Comment by jamstooks** [comment]
I think we won't get to this by the beta, but let's notify our testers that it is planned for the release...

**Comment by jamstooks** [comment]
There's a nice little toggle switch in the top left now for metric values.

**Comment by peltonc** [comment]
Selecting metric units negates percentage-based views. In other words, charts that include % as a unit are empty when metric units are selected.

**Comment by rerb** [comment]
@peltonc - this appears to be fixed, please confirm.

**Comment by jamstooks** [comment]
@peltonc @rerb This is only just fixed. Still deploying to stage...

**Comment by jamstooks** [comment]
It turns out the issue is with the STARS data. There are a number of cases in the STARS app where the metric and imperial values do not match when they should (when the units are "percentage" or empty).

@rerb To see this in action, use the [ns_fault_check](https://github.com/AASHE/stars/blob/start-etl/stars/apps/bt_etl/management/commands/ns_fault_check.py) management command that looks for `NumericSubmissions` where the metric value differs from the imperial value, but there are no units (or the unit is %). In those cases the values should match, or the metric_value should be `None`.

I have rigged the ETL script to check for this and fix it in the data that's being exported, but it's definitely worth looking into on the STARS side of things.

**Comment by jamstooks** [comment]
Ok, this is closed. I'll have 9hrs in the Paris airport tomorrow, so if you see an issue, let me know and I'd be happy to dive into it...
