### ISSUE TITLE
Option to create group from selection

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#68]
There doesn’t seem to be a way to bulk add a selection to a group. I had to do it one by one, which is kind of tedious.

**Comment by peltonc** [comment]
The order of the group in my selection appears to be based on the order in which I selected them on the Filters pane. FOR DISCUSSION: Would it be better if the selection was organized alphabetically by default?

**Comment by dodget** [comment]
In order to accomplish this, I will produce the following:

In `Selection` tab, on `Selected Reports` table, there are two column headers (Institution Name, Reports). I will add a third column header "Add all to group." It will function as a button to add all selections to a group.

This seems like the simplest solution.

**Comment by dodget** [comment]
Working locally. Will be pushed to dev server with next deploy.

**Comment by dodget** [comment]
Deployed to stars-bt-dev. Closing.
